### ISSUE TITLE
Grid points issues in LWA flux function

### ISSUE THREAD

**Issue by slubis** [csyhuang/hn2016_falwa#10]
Hi Clare,

Thanks for the clean and useful codes/subroutines. It seems that the functions do not work properly for the **even** grid points, but works well for **odd** grid points. Could you please check it? Probably there is a minor bug somewhere but I can not find :)

Thanks, Clare!

**Comment by csyhuang** [comment]
Hi Sandro,

Thanks for reporting. I intentionally make the subroutine display error message when the grid points are **even** (that the origin is not included in the grid):

```python
if sum(ylat==0)==0:
    raise TypeError("ylat must include the equator (i.e. degree 0)")
```

I did this because the inversion algorithm requires lat=0 to be on the grid point. I am going to include a procedure to interpolate the input field on the desired grid if lat=0 is not on the given grid. This will be a feature to include in the next version (likely v0.3.3).

**Comment by csyhuang** [comment]
The new release v0.3.5 has addressed this issue. Please update your version of package by using
```
git pull
```

Let me know if you have other suggestions. :)
