### ISSUE TITLE
Add diabatic heating in the LWA budget

### ISSUE THREAD

**Issue by chauncy-git** [csyhuang/hn2016_falwa#111]
Dear Huang, could you please add diabatic heating in the LWA budget to the package as the Eq (2) in Wang et al. (2021) (https://doi.org/10.1029/2020GL091727), as we sometimes want to quantify the contribution of diabatic heating. Thank you!

**Comment by csyhuang** [comment]
We will soon release a version of diabatic heating calculation in an upcoming manuscript (Lubis et al.), which we take in $\theta$ (in $1/s^2$, as in [Lubis et al 2018](https://journals.ametsoc.org/view/journals/atsc/75/11/jas-d-18-0138.1.xml) eq.6) as input (instead of $\dot{Q}$ ($K/s$) in Wang et al. 2021). You can use the new functionality to compute diabatic heating from $\dot{Q}$.

**Comment by chauncy-git** [comment]
@csyhuang Thanks. It's a great news and I can't wait to see the newer version.

**Comment by csyhuang** [comment]
@chauncy-git FYI announcement about this repo will be sent via email if you sign up [here](https://goo.gl/forms/5L8fv0mUordugq6v2). You can also follow this repo to get all the updates.

**Comment by csyhuang** [comment]
The code used is included in 640960e . This ticket will be close.
