### ISSUE TITLE
Verify that all example notebooks and scripts are working

### ISSUE THREAD

**Issue by csyhuang** [csyhuang/hn2016_falwa#66]
All netCDF files used in example notebooks/scripts can be found in my Dropbox:
https://www.dropbox.com/scl/fo/b84pwlr7zzsndq8mpthd8/h?dl=0&rlkey=f8c1gm2xaxvx3c7cf06vop6or
Verify that all example notebooks (`notebooks/`) and scripts (`scripts/`) on branch `release0.7.0` are producing expected results.

**Comment by chpolste** [comment]
I have two suggestions while the notebooks are being checked anyway:

- Use cartopy instead of basemap in `notebooks/simple/Example_qgpv.ipynb`. Basemap has been deprecated for a while now.
- It might be nice to add rendered versions of the notebooks to the documentation page with `nbsphinx`. I've done this for other projects and it's really convenient to have everything in one place. I would assume readthedocs supports this.

Let me know if I should set this up in a pull request.

**Comment by csyhuang** [comment]
Thanks Christopher for incorporating `nbsphinx` in #71 ! Given the time constraint, I will leave the first item for the next release: #75 . I've verified that the notebooks are working for v0.7.0 so I'll close this ticket now.
